// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FriendshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendName    string                 `protobuf:"bytes,2,opt,name=friendName,proto3" json:"friendName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendshipRequest) Reset() {
	*x = FriendshipRequest{}
	mi := &file_pkg_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipRequest) ProtoMessage() {}

func (x *FriendshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipRequest.ProtoReflect.Descriptor instead.
func (*FriendshipRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *FriendshipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendshipRequest) GetFriendName() string {
	if x != nil {
		return x.FriendName
	}
	return ""
}

type FriendshipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      string                 `protobuf:"bytes,1,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendshipResponse) Reset() {
	*x = FriendshipResponse{}
	mi := &file_pkg_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendshipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendshipResponse) ProtoMessage() {}

func (x *FriendshipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendshipResponse.ProtoReflect.Descriptor instead.
func (*FriendshipResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *FriendshipResponse) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *FriendshipResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_pkg_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_pkg_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_pkg_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_pkg_proto_user_proto protoreflect.FileDescriptor

const file_pkg_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/user.proto\x12\x04user\"K\n" +
	"\x11FriendshipRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"friendName\x18\x02 \x01(\tR\n" +
	"friendName\"F\n" +
	"\x12FriendshipResponse\x12\x1a\n" +
	"\bFriendId\x18\x01 \x01(\tR\bFriendId\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05Email\"\x1d\n" +
	"\vUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\fTokenRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"P\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername2\xc2\x01\n" +
	"\vUserService\x124\n" +
	"\vGetUserById\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x127\n" +
	"\rValidateToken\x12\x12.user.TokenRequest\x1a\x12.user.UserResponse\x12D\n" +
	"\x0fCheckFriendship\x12\x17.user.FriendshipRequest\x1a\x18.user.FriendshipResponseB+Z)github.com/S0rgi/Gainly_Avatars/pkg/protob\x06proto3"

var (
	file_pkg_proto_user_proto_rawDescOnce sync.Once
	file_pkg_proto_user_proto_rawDescData []byte
)

func file_pkg_proto_user_proto_rawDescGZIP() []byte {
	file_pkg_proto_user_proto_rawDescOnce.Do(func() {
		file_pkg_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_user_proto_rawDesc), len(file_pkg_proto_user_proto_rawDesc)))
	})
	return file_pkg_proto_user_proto_rawDescData
}

var file_pkg_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_user_proto_goTypes = []any{
	(*FriendshipRequest)(nil),  // 0: user.FriendshipRequest
	(*FriendshipResponse)(nil), // 1: user.FriendshipResponse
	(*UserRequest)(nil),        // 2: user.UserRequest
	(*TokenRequest)(nil),       // 3: user.TokenRequest
	(*UserResponse)(nil),       // 4: user.UserResponse
}
var file_pkg_proto_user_proto_depIdxs = []int32{
	2, // 0: user.UserService.GetUserById:input_type -> user.UserRequest
	3, // 1: user.UserService.ValidateToken:input_type -> user.TokenRequest
	0, // 2: user.UserService.CheckFriendship:input_type -> user.FriendshipRequest
	4, // 3: user.UserService.GetUserById:output_type -> user.UserResponse
	4, // 4: user.UserService.ValidateToken:output_type -> user.UserResponse
	1, // 5: user.UserService.CheckFriendship:output_type -> user.FriendshipResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_user_proto_init() }
func file_pkg_proto_user_proto_init() {
	if File_pkg_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_user_proto_rawDesc), len(file_pkg_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_user_proto_goTypes,
		DependencyIndexes: file_pkg_proto_user_proto_depIdxs,
		MessageInfos:      file_pkg_proto_user_proto_msgTypes,
	}.Build()
	File_pkg_proto_user_proto = out.File
	file_pkg_proto_user_proto_goTypes = nil
	file_pkg_proto_user_proto_depIdxs = nil
}
